#!/usr/bin/sh -e

set -x

uv run --group lint ruff format --check --diff src/starlette_caches tests
uv run --group lint ruff check src/starlette_caches tests
uv run --group types mypy src/starlette_caches tests