#!/bin/sh -e


VERSION="$(hatch version)"

hatch clean

hatch build
hatch publish
hatch run docs:deploy

echo "You probably want to also tag the version now:"
echo "git tag -a ${VERSION} -m 'version ${VERSION}'"
echo "git push --tags"

scripts/clean
